### ISSUE TITLE
Cannot run tests

### ISSUE THREAD

**Issue by OmgImAlexis** [Lesterpig/sockpress#21]
I'm trying to run the tests from this package but keep hitting an issue.

```
yarn run v1.12.3
$ mocha -t 5000 -R dot -b -g '\(HTTP\)' && mocha -t 10000 -R dot -b -g 'HTTPS'


  ․․

  1 passing (17ms)
  1 failing

  1) Sockpress (HTTP) "before each" hook: start for "should be able to get a page":
     Error [ERR_SERVER_ALREADY_LISTEN]: Listen method has been called more than once without closing.
      at Server.listen (net.js:1372:11)
      at Function._app.listen (lib/index.js:64:27)
      at Context.start (test/scripts/http.js:151:23)



error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by OmgImAlexis** [comment]
I've also converted this package to an ES6 module [here](https://github.com/Lesterpig/sockpress/compare/master...OmgImAlexis:master?w=1) and the does fix the above issue as it cleanly separates the two tests.

I do end up with this though. I'm not sure if this is possibly an underlying bug or something I've caused.

```
yarn run v1.12.3
$ mocha -r esm -t 5000 -R dot -b -g '\(HTTP\)' && mocha -r esm -t 10000 -R dot -b -g 'HTTPS'


  ․․․․․

  4 passing (695ms)
  1 failing

  1) Sockpress (HTTP) "after each" hook:
     Uncaught Error: Error: xhr post error
      at Socket.<anonymous> (test/common.js:43:23)
      at Socket.Emitter.emit (node_modules/component-emitter/index.js:133:20)
      at Socket.emit (node_modules/socket.io-client/lib/socket.js:136:10)
      at Manager.emitAll (node_modules/socket.io-client/lib/manager.js:82:27)
      at Manager.onerror (node_modules/socket.io-client/lib/manager.js:356:8)
      at Socket.<anonymous> (node_modules/component-bind/index.js:21:15)
      at Socket.Emitter.emit (node_modules/component-emitter/index.js:133:20)
      at Socket.onError (node_modules/engine.io-client/lib/socket.js:685:8)
      at XHR.<anonymous> (node_modules/engine.io-client/lib/socket.js:276:10)
      at XHR.Emitter.emit (node_modules/component-emitter/index.js:133:20)
      at XHR.Transport.onError (node_modules/engine.io-client/lib/transport.js:67:8)
      at Request.<anonymous> (node_modules/engine.io-client/lib/transports/polling-xhr.js:109:10)
      at Request.Emitter.emit (node_modules/component-emitter/index.js:133:20)
      at Request.onError (node_modules/engine.io-client/lib/transports/polling-xhr.js:309:8)
      at Timeout._onTimeout (node_modules/engine.io-client/lib/transports/polling-xhr.js:256:18)



error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Lesterpig** [comment]
Thanks for your report! I need to update tests quite regularly given express and socket.io evolutions. I'll try to find some time to look into this issue, don't hesitate to propose your ES6 changes as a pull request, this would be very cool for this library :+1:
